/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GroupAuthorizationEnum } from './GroupAuthorizationEnum';
import {
    GroupAuthorizationEnumFromJSON,
    GroupAuthorizationEnumFromJSONTyped,
    GroupAuthorizationEnumToJSON,
} from './GroupAuthorizationEnum';

/**
 * 
 * @export
 * @interface AddUserGroupRequest
 */
export interface AddUserGroupRequest {
    /**
     * 
     * @type {number}
     * @memberof AddUserGroupRequest
     */
    userId: number;
    /**
     * 
     * @type {GroupAuthorizationEnum}
     * @memberof AddUserGroupRequest
     */
    authorization: GroupAuthorizationEnum;
}

/**
 * Check if a given object implements the AddUserGroupRequest interface.
 */
export function instanceOfAddUserGroupRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "authorization" in value;

    return isInstance;
}

export function AddUserGroupRequestFromJSON(json: any): AddUserGroupRequest {
    return AddUserGroupRequestFromJSONTyped(json, false);
}

export function AddUserGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserGroupRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'authorization': GroupAuthorizationEnumFromJSON(json['authorization']),
    };
}

export function AddUserGroupRequestToJSON(value?: AddUserGroupRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'authorization': GroupAuthorizationEnumToJSON(value.authorization),
    };
}

