/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankAccountIndexDTO
 */
export interface BankAccountIndexDTO {
    /**
     * 
     * @type {number}
     * @memberof BankAccountIndexDTO
     */
    accountId: number;
    /**
     * 
     * @type {string}
     * @memberof BankAccountIndexDTO
     */
    accountName: string;
    /**
     * 
     * @type {number}
     * @memberof BankAccountIndexDTO
     */
    baseAmountDecimal: number;
}

/**
 * Check if a given object implements the BankAccountIndexDTO interface.
 */
export function instanceOfBankAccountIndexDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountId" in value;
    isInstance = isInstance && "accountName" in value;
    isInstance = isInstance && "baseAmountDecimal" in value;

    return isInstance;
}

export function BankAccountIndexDTOFromJSON(json: any): BankAccountIndexDTO {
    return BankAccountIndexDTOFromJSONTyped(json, false);
}

export function BankAccountIndexDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccountIndexDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'accountName': json['accountName'],
        'baseAmountDecimal': json['baseAmountDecimal'],
    };
}

export function BankAccountIndexDTOToJSON(value?: BankAccountIndexDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountId': value.accountId,
        'accountName': value.accountName,
        'baseAmountDecimal': value.baseAmountDecimal,
    };
}

