/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BankAccountIndexDTO } from './BankAccountIndexDTO';
import {
    BankAccountIndexDTOFromJSON,
    BankAccountIndexDTOFromJSONTyped,
    BankAccountIndexDTOToJSON,
} from './BankAccountIndexDTO';
import type { GroupIndexDTO } from './GroupIndexDTO';
import {
    GroupIndexDTOFromJSON,
    GroupIndexDTOFromJSONTyped,
    GroupIndexDTOToJSON,
} from './GroupIndexDTO';

/**
 * 
 * @export
 * @interface BankAccountDTO
 */
export interface BankAccountDTO {
    /**
     * 
     * @type {GroupIndexDTO}
     * @memberof BankAccountDTO
     */
    groupIndexDTO: GroupIndexDTO;
    /**
     * 
     * @type {BankAccountIndexDTO}
     * @memberof BankAccountDTO
     */
    accountIndexDTO: BankAccountIndexDTO;
}

/**
 * Check if a given object implements the BankAccountDTO interface.
 */
export function instanceOfBankAccountDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "groupIndexDTO" in value;
    isInstance = isInstance && "accountIndexDTO" in value;

    return isInstance;
}

export function BankAccountDTOFromJSON(json: any): BankAccountDTO {
    return BankAccountDTOFromJSONTyped(json, false);
}

export function BankAccountDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccountDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupIndexDTO': GroupIndexDTOFromJSON(json['groupIndexDTO']),
        'accountIndexDTO': BankAccountIndexDTOFromJSON(json['accountIndexDTO']),
    };
}

export function BankAccountDTOToJSON(value?: BankAccountDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groupIndexDTO': GroupIndexDTOToJSON(value.groupIndexDTO),
        'accountIndexDTO': BankAccountIndexDTOToJSON(value.accountIndexDTO),
    };
}

