/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BankAccountIndexDTO } from './BankAccountIndexDTO';
import {
    BankAccountIndexDTOFromJSON,
    BankAccountIndexDTOFromJSONTyped,
    BankAccountIndexDTOToJSON,
} from './BankAccountIndexDTO';
import type { GroupIndexDTO } from './GroupIndexDTO';
import {
    GroupIndexDTOFromJSON,
    GroupIndexDTOFromJSONTyped,
    GroupIndexDTOToJSON,
} from './GroupIndexDTO';

/**
 * 
 * @export
 * @interface BankAccountGroupDTO
 */
export interface BankAccountGroupDTO {
    /**
     * 
     * @type {GroupIndexDTO}
     * @memberof BankAccountGroupDTO
     */
    groupIndexDTO: GroupIndexDTO;
    /**
     * 
     * @type {Array<BankAccountIndexDTO>}
     * @memberof BankAccountGroupDTO
     */
    accountIndexDTOs: Array<BankAccountIndexDTO>;
}

/**
 * Check if a given object implements the BankAccountGroupDTO interface.
 */
export function instanceOfBankAccountGroupDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "groupIndexDTO" in value;
    isInstance = isInstance && "accountIndexDTOs" in value;

    return isInstance;
}

export function BankAccountGroupDTOFromJSON(json: any): BankAccountGroupDTO {
    return BankAccountGroupDTOFromJSONTyped(json, false);
}

export function BankAccountGroupDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccountGroupDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupIndexDTO': GroupIndexDTOFromJSON(json['groupIndexDTO']),
        'accountIndexDTOs': ((json['accountIndexDTOs'] as Array<any>).map(BankAccountIndexDTOFromJSON)),
    };
}

export function BankAccountGroupDTOToJSON(value?: BankAccountGroupDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groupIndexDTO': GroupIndexDTOToJSON(value.groupIndexDTO),
        'accountIndexDTOs': ((value.accountIndexDTOs as Array<any>).map(BankAccountIndexDTOToJSON)),
    };
}

