/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.13.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankAccountIndexDTO
 */
export interface BankAccountIndexDTO {
    /**
     * 
     * @type {string}
     * @memberof BankAccountIndexDTO
     */
    bankAccountName: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountIndexDTO
     */
    bankAccountId: string;
    /**
     * 
     * @type {number}
     * @memberof BankAccountIndexDTO
     */
    decimalBaseAmount: number;
}

/**
 * Check if a given object implements the BankAccountIndexDTO interface.
 */
export function instanceOfBankAccountIndexDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bankAccountName" in value;
    isInstance = isInstance && "bankAccountId" in value;
    isInstance = isInstance && "decimalBaseAmount" in value;

    return isInstance;
}

export function BankAccountIndexDTOFromJSON(json: any): BankAccountIndexDTO {
    return BankAccountIndexDTOFromJSONTyped(json, false);
}

export function BankAccountIndexDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccountIndexDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bankAccountName': json['bankAccountName'],
        'bankAccountId': json['bankAccountId'],
        'decimalBaseAmount': json['decimalBaseAmount'],
    };
}

export function BankAccountIndexDTOToJSON(value?: BankAccountIndexDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bankAccountName': value.bankAccountName,
        'bankAccountId': value.bankAccountId,
        'decimalBaseAmount': value.decimalBaseAmount,
    };
}

