/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTransactionRequest
 */
export interface CreateTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTransactionRequest
     */
    bankAccountId: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTransactionRequest
     */
    decimalAmount: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTransactionRequest
     */
    comment?: string;
}

/**
 * Check if a given object implements the CreateTransactionRequest interface.
 */
export function instanceOfCreateTransactionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bankAccountId" in value;
    isInstance = isInstance && "decimalAmount" in value;

    return isInstance;
}

export function CreateTransactionRequestFromJSON(json: any): CreateTransactionRequest {
    return CreateTransactionRequestFromJSONTyped(json, false);
}

export function CreateTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTransactionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bankAccountId': json['BankAccountId'],
        'decimalAmount': json['DecimalAmount'],
        'comment': !exists(json, 'Comment') ? undefined : json['Comment'],
    };
}

export function CreateTransactionRequestToJSON(value?: CreateTransactionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BankAccountId': value.bankAccountId,
        'DecimalAmount': value.decimalAmount,
        'Comment': value.comment,
    };
}

