/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FunctionalExceptionDTO
 */
export interface FunctionalExceptionDTO {
    /**
     * 
     * @type {number}
     * @memberof FunctionalExceptionDTO
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof FunctionalExceptionDTO
     */
    details: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionalExceptionDTO
     */
    exception: string;
    /**
     * 
     * @type {string}
     * @memberof FunctionalExceptionDTO
     */
    message: string;
    /**
     * 
     * @type {Date}
     * @memberof FunctionalExceptionDTO
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the FunctionalExceptionDTO interface.
 */
export function instanceOfFunctionalExceptionDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "details" in value;
    isInstance = isInstance && "exception" in value;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "timestamp" in value;

    return isInstance;
}

export function FunctionalExceptionDTOFromJSON(json: any): FunctionalExceptionDTO {
    return FunctionalExceptionDTOFromJSONTyped(json, false);
}

export function FunctionalExceptionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionalExceptionDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'details': json['details'],
        'exception': json['exception'],
        'message': json['message'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function FunctionalExceptionDTOToJSON(value?: FunctionalExceptionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'details': value.details,
        'exception': value.exception,
        'message': value.message,
        'timestamp': (value.timestamp.toISOString()),
    };
}

