/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BankAccountIndexDTO } from './BankAccountIndexDTO';
import {
    BankAccountIndexDTOFromJSON,
    BankAccountIndexDTOFromJSONTyped,
    BankAccountIndexDTOToJSON,
} from './BankAccountIndexDTO';
import type { GroupIndexDTO } from './GroupIndexDTO';
import {
    GroupIndexDTOFromJSON,
    GroupIndexDTOFromJSONTyped,
    GroupIndexDTOToJSON,
} from './GroupIndexDTO';

/**
 * 
 * @export
 * @interface GroupBankAcccountIndexDTO
 */
export interface GroupBankAcccountIndexDTO {
    /**
     * 
     * @type {GroupIndexDTO}
     * @memberof GroupBankAcccountIndexDTO
     */
    groupeIndex: GroupIndexDTO;
    /**
     * 
     * @type {Array<BankAccountIndexDTO>}
     * @memberof GroupBankAcccountIndexDTO
     */
    bankAccountIndexList: Array<BankAccountIndexDTO>;
}

/**
 * Check if a given object implements the GroupBankAcccountIndexDTO interface.
 */
export function instanceOfGroupBankAcccountIndexDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "groupeIndex" in value;
    isInstance = isInstance && "bankAccountIndexList" in value;

    return isInstance;
}

export function GroupBankAcccountIndexDTOFromJSON(json: any): GroupBankAcccountIndexDTO {
    return GroupBankAcccountIndexDTOFromJSONTyped(json, false);
}

export function GroupBankAcccountIndexDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupBankAcccountIndexDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupeIndex': GroupIndexDTOFromJSON(json['groupeIndex']),
        'bankAccountIndexList': ((json['bankAccountIndexList'] as Array<any>).map(BankAccountIndexDTOFromJSON)),
    };
}

export function GroupBankAcccountIndexDTOToJSON(value?: GroupBankAcccountIndexDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groupeIndex': GroupIndexDTOToJSON(value.groupeIndex),
        'bankAccountIndexList': ((value.bankAccountIndexList as Array<any>).map(BankAccountIndexDTOToJSON)),
    };
}

