/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GroupAuthorizationEnum = {
    Read: 'READ',
    Write: 'WRITE',
    Admin: 'ADMIN'
} as const;
export type GroupAuthorizationEnum = typeof GroupAuthorizationEnum[keyof typeof GroupAuthorizationEnum];


export function GroupAuthorizationEnumFromJSON(json: any): GroupAuthorizationEnum {
    return GroupAuthorizationEnumFromJSONTyped(json, false);
}

export function GroupAuthorizationEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupAuthorizationEnum {
    return json as GroupAuthorizationEnum;
}

export function GroupAuthorizationEnumToJSON(value?: GroupAuthorizationEnum | null): any {
    return value as any;
}

