/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserGroupDTO } from './UserGroupDTO';
import {
    UserGroupDTOFromJSON,
    UserGroupDTOFromJSONTyped,
    UserGroupDTOToJSON,
} from './UserGroupDTO';

/**
 * 
 * @export
 * @interface GroupDTO
 */
export interface GroupDTO {
    /**
     * 
     * @type {string}
     * @memberof GroupDTO
     */
    groupId: string;
    /**
     * 
     * @type {string}
     * @memberof GroupDTO
     */
    groupName: string;
    /**
     * 
     * @type {Array<UserGroupDTO>}
     * @memberof GroupDTO
     */
    users: Array<UserGroupDTO>;
}

/**
 * Check if a given object implements the GroupDTO interface.
 */
export function instanceOfGroupDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "groupId" in value;
    isInstance = isInstance && "groupName" in value;
    isInstance = isInstance && "users" in value;

    return isInstance;
}

export function GroupDTOFromJSON(json: any): GroupDTO {
    return GroupDTOFromJSONTyped(json, false);
}

export function GroupDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
        'groupName': json['groupName'],
        'users': ((json['users'] as Array<any>).map(UserGroupDTOFromJSON)),
    };
}

export function GroupDTOToJSON(value?: GroupDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groupId': value.groupId,
        'groupName': value.groupName,
        'users': ((value.users as Array<any>).map(UserGroupDTOToJSON)),
    };
}

