/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionIndexDTO
 */
export interface TransactionIndexDTO {
    /**
     * 
     * @type {number}
     * @memberof TransactionIndexDTO
     */
    transactionId: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionIndexDTO
     */
    amountInCents: number;
    /**
     * 
     * @type {Date}
     * @memberof TransactionIndexDTO
     */
    date: Date;
}

/**
 * Check if a given object implements the TransactionIndexDTO interface.
 */
export function instanceOfTransactionIndexDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "transactionId" in value;
    isInstance = isInstance && "amountInCents" in value;
    isInstance = isInstance && "date" in value;

    return isInstance;
}

export function TransactionIndexDTOFromJSON(json: any): TransactionIndexDTO {
    return TransactionIndexDTOFromJSONTyped(json, false);
}

export function TransactionIndexDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionIndexDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transactionId': json['transactionId'],
        'amountInCents': json['amountInCents'],
        'date': (new Date(json['date'])),
    };
}

export function TransactionIndexDTOToJSON(value?: TransactionIndexDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transactionId': value.transactionId,
        'amountInCents': value.amountInCents,
        'date': (value.date.toISOString().substring(0,10)),
    };
}

