/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionUpdateRequest
 */
export interface TransactionUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof TransactionUpdateRequest
     */
    amountInCents?: number;
    /**
     * 
     * @type {Date}
     * @memberof TransactionUpdateRequest
     */
    date?: Date;
}

/**
 * Check if a given object implements the TransactionUpdateRequest interface.
 */
export function instanceOfTransactionUpdateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TransactionUpdateRequestFromJSON(json: any): TransactionUpdateRequest {
    return TransactionUpdateRequestFromJSONTyped(json, false);
}

export function TransactionUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amountInCents': !exists(json, 'amountInCents') ? undefined : json['amountInCents'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
    };
}

export function TransactionUpdateRequestToJSON(value?: TransactionUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amountInCents': value.amountInCents,
        'date': value.date === undefined ? undefined : (value.date.toISOString().substring(0,10)),
    };
}

