/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionCreationRequest
 */
export interface TransactionCreationRequest {
    /**
     * 
     * @type {number}
     * @memberof TransactionCreationRequest
     */
    accountId: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionCreationRequest
     */
    amountInCents: number;
    /**
     * 
     * @type {Date}
     * @memberof TransactionCreationRequest
     */
    date: Date;
}

/**
 * Check if a given object implements the TransactionCreationRequest interface.
 */
export function instanceOfTransactionCreationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountId" in value;
    isInstance = isInstance && "amountInCents" in value;
    isInstance = isInstance && "date" in value;

    return isInstance;
}

export function TransactionCreationRequestFromJSON(json: any): TransactionCreationRequest {
    return TransactionCreationRequestFromJSONTyped(json, false);
}

export function TransactionCreationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionCreationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'amountInCents': json['amountInCents'],
        'date': (new Date(json['date'])),
    };
}

export function TransactionCreationRequestToJSON(value?: TransactionCreationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountId': value.accountId,
        'amountInCents': value.amountInCents,
        'date': (value.date.toISOString().substring(0,10)),
    };
}

