/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BankAccountIndexDTO } from './BankAccountIndexDTO';
import {
    BankAccountIndexDTOFromJSON,
    BankAccountIndexDTOFromJSONTyped,
    BankAccountIndexDTOToJSON,
} from './BankAccountIndexDTO';
import type { TransactionIndexDTO } from './TransactionIndexDTO';
import {
    TransactionIndexDTOFromJSON,
    TransactionIndexDTOFromJSONTyped,
    TransactionIndexDTOToJSON,
} from './TransactionIndexDTO';

/**
 * 
 * @export
 * @interface TransactionDTO
 */
export interface TransactionDTO {
    /**
     * 
     * @type {BankAccountIndexDTO}
     * @memberof TransactionDTO
     */
    accountIndexDTO: BankAccountIndexDTO;
    /**
     * 
     * @type {TransactionIndexDTO}
     * @memberof TransactionDTO
     */
    transactionIndexDTO: TransactionIndexDTO;
}

/**
 * Check if a given object implements the TransactionDTO interface.
 */
export function instanceOfTransactionDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountIndexDTO" in value;
    isInstance = isInstance && "transactionIndexDTO" in value;

    return isInstance;
}

export function TransactionDTOFromJSON(json: any): TransactionDTO {
    return TransactionDTOFromJSONTyped(json, false);
}

export function TransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountIndexDTO': BankAccountIndexDTOFromJSON(json['accountIndexDTO']),
        'transactionIndexDTO': TransactionIndexDTOFromJSON(json['transactionIndexDTO']),
    };
}

export function TransactionDTOToJSON(value?: TransactionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountIndexDTO': BankAccountIndexDTOToJSON(value.accountIndexDTO),
        'transactionIndexDTO': TransactionIndexDTOToJSON(value.transactionIndexDTO),
    };
}

