/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionDTO
 */
export interface TransactionDTO {
    /**
     * 
     * @type {string}
     * @memberof TransactionDTO
     */
    transactionId: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionDTO
     */
    bankAccountId: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionDTO
     */
    decimalAmount: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionDTO
     */
    comment?: string;
}

/**
 * Check if a given object implements the TransactionDTO interface.
 */
export function instanceOfTransactionDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "transactionId" in value;
    isInstance = isInstance && "bankAccountId" in value;
    isInstance = isInstance && "decimalAmount" in value;

    return isInstance;
}

export function TransactionDTOFromJSON(json: any): TransactionDTO {
    return TransactionDTOFromJSONTyped(json, false);
}

export function TransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transactionId': json['TransactionId'],
        'bankAccountId': json['BankAccountId'],
        'decimalAmount': json['DecimalAmount'],
        'comment': !exists(json, 'Comment') ? undefined : json['Comment'],
    };
}

export function TransactionDTOToJSON(value?: TransactionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TransactionId': value.transactionId,
        'BankAccountId': value.bankAccountId,
        'DecimalAmount': value.decimalAmount,
        'Comment': value.comment,
    };
}

