/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';
import type { UserGroupRightEnum } from './UserGroupRightEnum';
import {
    UserGroupRightEnumFromJSON,
    UserGroupRightEnumFromJSONTyped,
    UserGroupRightEnumToJSON,
} from './UserGroupRightEnum';

/**
 * 
 * @export
 * @interface UserGroupRightDTO
 */
export interface UserGroupRightDTO {
    /**
     * 
     * @type {string}
     * @memberof UserGroupRightDTO
     */
    id: string;
    /**
     * 
     * @type {UserDTO}
     * @memberof UserGroupRightDTO
     */
    user: UserDTO;
    /**
     * 
     * @type {UserGroupRightEnum}
     * @memberof UserGroupRightDTO
     */
    right: UserGroupRightEnum;
}

/**
 * Check if a given object implements the UserGroupRightDTO interface.
 */
export function instanceOfUserGroupRightDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "right" in value;

    return isInstance;
}

export function UserGroupRightDTOFromJSON(json: any): UserGroupRightDTO {
    return UserGroupRightDTOFromJSONTyped(json, false);
}

export function UserGroupRightDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGroupRightDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user': UserDTOFromJSON(json['user']),
        'right': UserGroupRightEnumFromJSON(json['right']),
    };
}

export function UserGroupRightDTOToJSON(value?: UserGroupRightDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'user': UserDTOToJSON(value.user),
        'right': UserGroupRightEnumToJSON(value.right),
    };
}

