version: "3.9"
services:
  swaggereditor:
    image: swaggerapi/swagger-editor:v4-latest
    container_name: swaggereditor_openapi
    ports:
      - '9680:8080'
    volumes:
      - ./openapi.yaml:/tmp/openapi.yaml
    environment:
      SWAGGER_FILE: /tmp/openapi.yaml
