openapi: 3.0.0
info:
  title: BankWiz API
  version: 0.3.0
  description: An API for accessing banking functionalities provided by BankWiz
servers:
  - url: 'http://localhost:8080/api'
tags:
  - name: User
    description: API endpoints for managing user information
security:
  - bearerAuth: []         # use the same name as above
paths:
  /user:
    get:
      tags:
        - User
      summary: Get the current user information
      operationId: getCurrentUserInfo
      responses:
        '200':
          description: Successfully retrieved user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '400':
          description: Invalid request. Please check the provided data.
  /user/checkregistration:
    get:
      tags:
        - User
      summary: Checks if the user is registered, and registers her if not.
      operationId: checkRegistration
      responses:
        '200':
          description: Successfully retrieved user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '400':
          description: Invalid request. Please check the provided data.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        email:
          type: string
          format: email
          example: johndoe@example.com
      required:
        - id
        - firstName
        - lastName
        - email