openapi: 3.0.0
info:
  title: BankWiz API
  version: 0.6.1
  description: An API for accessing banking functionalities provided by BankWiz
servers:
  - url: http://localhost:8080
    description: Local developpement (server)
tags:
  - name: UserService
    description: API endpoints for managing user information
  - name: GroupService
    description: API endpoints for managing group information
security:
  - oauth2:
    - openid
    - profile
    - email
paths:
  /user:
    get:
      tags:
        - UserService
      summary: Get the current user information
      operationId: getCurrentUserInfo
      responses:
        '200':
          description: Successfully retrieved user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '400':
          description: Invalid request. Please check the provided data.
  /user/checkregistration:
    get:
      tags:
        - UserService
      summary: Checks if the user is registered, and registers her if not.
      operationId: checkRegistration
      responses:
        '200':
          description: Successfully retrieved user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '400':
          description: Invalid request. Please check the provided data.
  /group:
    post:
      tags:
        - GroupService
      summary: Create a group
      operationId: createGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupCreationRequest'
      responses:
        '201':
          description: Group created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupIndexDTO'
        '400':
          description: Invalid request. Please check the provided data.
  /group/{id}:
    get:
      tags:
        - GroupService
      summary: Get a group details
      operationId: getGroupDetails
      parameters:
        - name: id
          in: path
          description: Group ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Get group
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupDetailsDTO'
        '400':
          description: Invalid request. Please check the provided data.
  /group/{id}/user:
    post:
      tags:
        - GroupService
      summary: Add user to group
      operationId: addUserGroup
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddUserGroupRequest'
      responses:
        '200':
          description: User added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserGroupRightDTO'
        '400':
          description: Invalid request. Please check the provided data.
  /group/groups:
    get:
      tags:
        - GroupService
      summary: Get all groups of user
      operationId: getUserGroups
      responses:
        '200':
          description: Get all groups of user
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/UserGroupRightDTO'
        '400':
          description: Invalid request. Please check the provided data.
components:
  securitySchemes:
    oauth2:   # <--- Arbitrary name for the security scheme. Used to refer to it from elsewhere.
      type: oauth2
      description: For more information, see https://api.slack.com/docs/oauth
      flows: 
        implicit:
          authorizationUrl: https://bankwiz-dev.eu.auth0.com/authorize?audience=Bankwiz_server
          scopes:
            openid: openid
            profile: profile
            email: email
  schemas:
    FunctionalExceptionDTO:
      type: object
      properties:
        status:
          type: integer
        details:
          type: string
        exception:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
      required:
        - status
        - details
        - exception
        - message
        - timestamp
    MethodArgumentNotValidExceptionDTO:
      type: object
      properties:
        status:
          type: integer
        details:
          type: string
        exception:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        field:
          type: string
        objectName:
          type: string
      required:
        - status
        - details
        - exception
        - message
        - timestamp
        - field
        - objectName
    GroupCreationRequest:
      type: object
      properties:
        groupName:
          type: string
      required:
        - groupName
    UserDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
          example: johndoe@example.com
      required:
        - id
        - email
    AddUserGroupRequest:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        right:
          $ref: '#/components/schemas/UserGroupRightEnum'
      required:
        - userId
        - right
    GroupIndexDTO:
      type: object
      properties:
        groupId:
          type: string
          format: uuid
        groupName:
          type: string
      required:
        - groupId
        - groupName
    UserGroupRightEnum:
      type: string
      enum:
        - READ
        - WRITE
        - ADMIN
    UserGroupRightDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user:
          $ref: '#/components/schemas/UserDTO'
        right:
          $ref: '#/components/schemas/UserGroupRightEnum'
      required:
        - id
        - user
        - right
    GroupDetailsDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        groupName:
          type: string
        usersRights:
          type: array
          items:
            $ref: '#/components/schemas/UserGroupRightDTO'
      required:
        - id
        - groupName
        - usersRights