/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BankAccountCreationRequest
 */
export interface BankAccountCreationRequest {
    /**
     * 
     * @type {number}
     * @memberof BankAccountCreationRequest
     */
    'groupId': number;
    /**
     * 
     * @type {string}
     * @memberof BankAccountCreationRequest
     */
    'accountName': string;
    /**
     * 
     * @type {number}
     * @memberof BankAccountCreationRequest
     */
    'baseAmountDecimal': number;
}

