/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BankAccountUpdateRequest
 */
export interface BankAccountUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof BankAccountUpdateRequest
     */
    'accountName'?: string;
    /**
     * 
     * @type {number}
     * @memberof BankAccountUpdateRequest
     */
    'baseAmountDecimal'?: number;
}

