/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BankAccountIndexDTO
 */
export interface BankAccountIndexDTO {
    /**
     * 
     * @type {string}
     * @memberof BankAccountIndexDTO
     */
    'bankAccountName': string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountIndexDTO
     */
    'bankAccountId': string;
}

