/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FunctionalExceptionDTO
 */
export interface FunctionalExceptionDTO {
    /**
     * 
     * @type {number}
     * @memberof FunctionalExceptionDTO
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof FunctionalExceptionDTO
     */
    'details': string;
    /**
     * 
     * @type {string}
     * @memberof FunctionalExceptionDTO
     */
    'exception': string;
    /**
     * 
     * @type {string}
     * @memberof FunctionalExceptionDTO
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof FunctionalExceptionDTO
     */
    'timestamp': string;
}

