/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserGroupDTO } from './user-group-dto';

/**
 * 
 * @export
 * @interface GroupDTO
 */
export interface GroupDTO {
    /**
     * 
     * @type {number}
     * @memberof GroupDTO
     */
    'groupId': number;
    /**
     * 
     * @type {string}
     * @memberof GroupDTO
     */
    'groupName': string;
    /**
     * 
     * @type {Array<UserGroupDTO>}
     * @memberof GroupDTO
     */
    'users': Array<UserGroupDTO>;
}

