/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupUpdateRequest
 */
export interface GroupUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof GroupUpdateRequest
     */
    'groupName'?: string;
}

