/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupIndexDTO
 */
export interface GroupIndexDTO {
    /**
     * 
     * @type {string}
     * @memberof GroupIndexDTO
     */
    'groupId': string;
    /**
     * 
     * @type {string}
     * @memberof GroupIndexDTO
     */
    'groupName': string;
}

