/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.2.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TransactionUpdateRequest
 */
export interface TransactionUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof TransactionUpdateRequest
     */
    'amountInCents'?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionUpdateRequest
     */
    'date'?: string;
}

