name: Setup action
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'maven'
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
    - name: Instal dependencies
      shell: bash
      run: npm ci