name: Generate package
on:
  push:
    branches:
      - '*'
env:
  USER_GITHUB_KEY: ${{ secrets.GITHUB_TOKEN }}
  CI: true
jobs:
  validate-openapi-spec:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: Validate spec
        run: npm run validate
  generate-java-server:
    needs:
      - validate-openapi-spec
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: clean
        run: npm run clean:java-server
      - name: generate
        run: npm run generate:java-server
      - name: build
        run: npm run build:java-server
  generate-fetch-client:
    needs:
      - validate-openapi-spec
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: clean
        run: npm run clean:fetch-client
      - name: generate
        run: npm run generate:fetch-client
      - name: build
        run: npm run build:fetch-client
  generate-doc:
    needs:
      - validate-openapi-spec
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: clean
        run: npm run clean:doc
      - name: generate
        run: npm run generate:doc
