name: Generate package
on:
  push:
    branches:
      - '*'
env:
  USER_GITHUB_KEY: ${{ secrets.GITHUB_TOKEN }}
  CI: true
jobs:
  check-openapi-spec:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Checkout Git repository
        uses: ./.github/tools/setup_action.yaml