name: Generate package
on:
  push:
    branches:
      - '*'
env:
  USER_GITHUB_KEY: ${{ secrets.GITHUB_TOKEN }}
  CI: true
jobs:
  validate-openapi-spec:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: Validate spec
        run: npm run validate